// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpNo-vAww11sfJOuIcjAXTuYFrGNr0McU',
    appId: '1:244669270812:web:48bbfbe1688d96fbac08d9',
    messagingSenderId: '244669270812',
    projectId: 'firstp-9068d',
    authDomain: 'firstp-9068d.firebaseapp.com',
    storageBucket: 'firstp-9068d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtOiOB3UP2CESmV9OeT9GxKjJEyB5I25o',
    appId: '1:244669270812:android:802f9f372a41d20bac08d9',
    messagingSenderId: '244669270812',
    projectId: 'firstp-9068d',
    storageBucket: 'firstp-9068d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKPgiAlAb0vZxA0sTO67mI7kKbTpB1ecw',
    appId: '1:244669270812:ios:d6b69e8c335de4c9ac08d9',
    messagingSenderId: '244669270812',
    projectId: 'firstp-9068d',
    storageBucket: 'firstp-9068d.appspot.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKPgiAlAb0vZxA0sTO67mI7kKbTpB1ecw',
    appId: '1:244669270812:ios:0cfa872ffbacbf8cac08d9',
    messagingSenderId: '244669270812',
    projectId: 'firstp-9068d',
    storageBucket: 'firstp-9068d.appspot.com',
    iosBundleId: 'com.example.admin.RunnerTests',
  );
}
